name: card_game_beta
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/field.jpg
    - assets/images/goalBottom.jpg
    - assets/images/goalTop.jpg
    - assets/images/players/0.jpg
    - assets/images/players/1.jpg
    - assets/images/players/2.jpg
    - assets/images/players/3.jpg
    - assets/images/players/4.jpg
    - assets/images/players/5.jpg
    - assets/images/players/6.jpg
    - assets/images/players/7.jpg
    - assets/images/players/8.jpg
    - assets/images/players/9.jpg
    - assets/images/players/10.jpg
    - assets/images/players/11.jpg
    - assets/images/players/12.jpg
    - assets/images/players/13.jpg
    - assets/images/players/14.jpg
    - assets/images/players/15.jpg
    - assets/images/players/16.jpg
    - assets/images/players/17.jpg
    - assets/images/players/18.jpg
    - assets/images/players/19.jpg
    - assets/images/players/20.jpg
    - assets/images/players/21.jpg
    - assets/images/players/22.jpg
    - assets/images/players/23.jpg
    - assets/images/players/24.jpg
    - assets/images/players/25.jpg
    - assets/images/players/26.jpg
    - assets/images/players/27.jpg
    - assets/images/players/28.jpg
    - assets/images/players/29.jpg
    - assets/images/players/30.jpg
    - assets/images/players/31.jpg
    - assets/images/players/32.jpg
    - assets/images/players/33.jpg
    - assets/images/players/34.jpg
    - assets/images/players/35.jpg
    - assets/images/players/36.jpg
    - assets/images/players/37.jpg
    - assets/images/players/38.jpg
    - assets/images/players/39.jpg
    - assets/images/players/40.jpg
    - assets/images/players/41.jpg
    - assets/images/players/42.jpg
    - assets/images/players/43.jpg
    - assets/images/players/44.jpg
    - assets/images/players/45.jpg
    - assets/images/players/46.jpg
    - assets/images/players/47.jpg
    - assets/images/players/48.jpg
    - assets/images/players/49.jpg
    - assets/images/players/50.jpg
    - assets/images/players/51.jpg
    - assets/images/players/52.jpg
    - assets/images/players/53.jpg
    - assets/images/players/54.jpg
    - assets/images/players/55.jpg
    - assets/images/players/56.jpg
    - assets/images/players/57.jpg
    - assets/images/players/58.jpg
    - assets/images/players/59.jpg
    - assets/sprites/players.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
